using DevExpress.XtraEditors;
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Drawing;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows.Forms;

namespace Project_USF
{
    public partial class Factoring_Chart : DevExpress.XtraEditors.XtraUserControl
    {
        public static Factoring_Chart _instance;

        public static Factoring_Chart Instance
        {
            get
            {
                if (_instance == null)
                    _instance = new Factoring_Chart();
                return _instance;
            }
        }
        public Factoring_Chart()
        {

            InitializeComponent();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource
            //sqlDataSource1.Fill();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill the SqlDataSource asynchronously
            //sqlDataSource1.FillAsync();
            // This line of code is generated by Data Source Configuration Wizard
            // Fill a SqlDataSource
            sqlDataSource1.Fill();
        }
    }
}
